
ej.base.enableRipple(true);

var sportsData = ['Menu', 'Excel', 'FilterBar'];
var dropDownListObject = new ej.dropdowns.DropDownList({
    dataSource: sportsData,
    change: ddChange,
    placeholder: "Select a Filter"
});
dropDownListObject.appendTo('#ddlelement1');

var data = [];
var fields = [];

for (var i = 1; i < 51; i++) {
    fields.push("Field" + i);
}

var dropDownListObject2 = new ej.dropdowns.DropDownList({
    dataSource: fields,
    placeholder: "Select a field"
});
dropDownListObject2.appendTo('#ddlelement2');

dataSource();

function dataSource() {
    let names = [
        'VINET',
        'TOMSP',
        'HANAR',
        'VICTE',
        'SUPRD',
        'HANAR',
        'CHOPS',
        'RICSU',
        'WELLI',
        'HILAA',
        'ERNSH',
        'CENTC',
        'OTTIK',
        'QUEDE',
        'RATTC',
        'ERNSH',
        'FOLKO',
        'BLONP',
        'WARTH',
        'FRANK',
        'GROSR',
        'WHITC',
        'WARTH',
        'SPLIR',
        'RATTC',
        'QUICK',
        'VINET',
        'MAGAA',
        'TORTU',
        'MORGK',
        'BERGS',
        'LEHMS',
        'BERGS',
        'ROMEY',
        'ROMEY',
        'LILAS',
        'LEHMS',
        'QUICK',
        'QUICK',
        'RICAR',
        'REGGC',
        'BSBEV',
        'COMMI',
        'QUEDE',
        'TRADH',
        'TORTU',
        'RATTC',
        'VINET',
        'LILAS',
        'BLONP',
        'HUNGO',
        'RICAR',
        'MAGAA',
        'WANDK',
        'SUPRD',
        'GODOS',
        'TORTU',
        'OLDWO',
        'ROMEY',
        'LONEP',
        'ANATR',
        'HUNGO',
        'THEBI',
        'DUMON',
        'WANDK',
        'QUICK',
        'RATTC',
        'ISLAT',
        'RATTC',
        'LONEP',
        'ISLAT',
        'TORTU',
        'WARTH',
        'ISLAT',
        'PERIC',
        'KOENE',
        'SAVEA',
        'KOENE',
        'BOLID',
        'FOLKO',
        'FURIB',
        'SPLIR',
        'LILAS',
        'BONAP',
        'MEREP',
        'WARTH',
        'VICTE',
        'HUNGO',
        'PRINI',
        'FRANK',
        'OLDWO',
        'MEREP',
        'BONAP',
        'SIMOB',
        'FRANK',
        'LEHMS',
        'WHITC',
        'QUICK',
        'RATTC',
        'FAMIA',
    ];
    const sport = [
        'Cricket',
        'Football',
        'Tennis',
        'Golf',
        'Chess',
        'Dodgeball',
        'Racket',
        'Archery',
        'Climbing',
        'Hunting',
        'Carrom',
        'Tag',
        'Novuss',
        'Subbuteo',
        'Baseball',
        'Madden NFL',
        'Shuffleboard',
        'Badminton',
        'Hockey',
        'Volleyball',
        'Table Tennis',
        'Golf',
        'Cycling',
        'Running',
        'Walking',
        'Wireball',
        'Town ball',
        'Tee ball',
        'Stool ball',
        'Stick ball',
    ];
    const country = [
        'India',
        'Australia',
        'Ballesteros',
        'Belgium',
        'Brazil',
        'England',
        'Ethiopia',
        'Finland',
        'France',
        'Germany',
        'Britain',
        'Argentina',
        'Jamaica',
        'Kenya',
        'Morocco',
        'Ireland',
        'Norway',
        'Philippines',
        'Portugal',
        'Romania',
        'Russia',
        'Scotland',
        'Scottish',
        'Serbia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Netherlands',
        'UK',
        'Ukraine',
        'US',
        'Wales',
        'West Indies',
        'China',
        'Hong Kong',
        'Italy',
        'Philippines',
        'Turkey',
        'Botswana',
        'Sri Lanka',
        'Algeria',
        'Bangladesh',
        'Egypt',
        'Malaysia',
    ];
    for (let i = 0; i < 800; i++) {
        data.push({
            SNo: i + 1,
            Field1: names[Math.floor(Math.random() * names.length)],
            Field2: 1967 + (i % 10),
            Field3: sport[Math.floor(Math.random() * sport.length)],
            Field4: country[Math.floor(Math.random() * country.length)],
            Field5: Math.floor(Math.random() * 2000),
            Field6: Math.floor(Math.random() * 1000),
            Field7: Math.floor(Math.random() * 100),
            Field8: Math.floor(Math.random() * 10),
            Field9: Math.floor(Math.random() * 10),
            Field10: Math.floor(Math.random() * 100),
            Field11: Math.floor(Math.random() * 100),
            Field12: Math.floor(Math.random() * 1000),
            Field13: Math.floor(Math.random() * 10),
            Field14: Math.floor(Math.random() * 10),
            Field15: Math.floor(Math.random() * 1000),
            Field16: Math.floor(Math.random() * 200),
            Field17: Math.floor(Math.random() * 300),
            Field18: Math.floor(Math.random() * 400),
            Field19: Math.floor(Math.random() * 500),
            Field20: Math.floor(Math.random() * 700),
            Field21: Math.floor(Math.random() * 800),
            Field22: Math.floor(Math.random() * 1000),
            Field23: Math.floor(Math.random() * 2000),
            Field24: Math.floor(Math.random() * 150),
            Field25: Math.floor(Math.random() * 1000),
            Field26: Math.floor(Math.random() * 100),
            Field27: Math.floor(Math.random() * 400),
            Field28: Math.floor(Math.random() * 600),
            Field29: Math.floor(Math.random() * 500),
            Field30: Math.floor(Math.random() * 300),
            Field31: Math.floor(Math.random() * 1000),
            Field32: Math.floor(Math.random() * 100),
            Field33: Math.floor(Math.random() * 100),
            Field34: Math.floor(Math.random() * 100),
            Field35: Math.floor(Math.random() * 10),
            Field36: Math.floor(Math.random() * 2000),
            Field37: Math.floor(Math.random() * 3000),
            Field38: Math.floor(Math.random() * 4000),
            Field39: Math.floor(Math.random() * 50),
            Field40: Math.floor(Math.random() * 70),
            Field41: Math.floor(Math.random() * 80),
            Field42: Math.floor(Math.random() * 10),
            Field43: Math.floor(Math.random() * 20),
            Field44: Math.floor(Math.random() * 10),
            Field45: Math.floor(Math.random() * 100),
            Field46: Math.floor(Math.random() * 10),
            Field47: Math.floor(Math.random() * 40),
            Field48: Math.floor(Math.random() * 600),
            Field49: Math.floor(Math.random() * 500),
            Field50: Math.floor(Math.random() * 300),
        });
    }
}

var grid = new ej.grids.Grid({
    dataSource: data,
    allowFiltering: true,
    allowSorting: true,
    filterSettings: { type: "Menu" },
    allowGrouping: true,
    allowResizing: true,
    allowReordering: true,
    editSettings: { allowEditing: true, allowAdding: true, allowDeleting: true },
    enableColumnVirtualization: true,
    allowPaging: true,
    toolbar: ['Add', 'Edit', 'Delete', 'Update', 'Cancel', "Search"],
    height: 300,
    // frozenColumns: 2,
    // frozenRows: 2,
    columns: [
        // { type: 'checkbox' },
        { field: 'SNo', isPrimaryKey: true, width: 140 },
        { field: 'Field1', width: 140 },
        { field: 'Field2', width: 140 },
        { field: 'Field3', width: 140 },
        { field: 'Field4', width: 140 },
        { field: 'Field5', width: 140 },
        { field: 'Field6', width: 140 },
        { field: 'Field7', width: 140 },
        { field: 'Field8', width: 140 },
        { field: 'Field9', width: 140 },
        { field: 'Field10', width: 140 },
        { field: 'Field11', width: 140 },
        { field: 'Field12', width: 140 },
        { field: 'Field13', width: 140 },
        { field: 'Field14', width: 140 },
        { field: 'Field15', width: 140 },
        { field: 'Field16', width: 140 },
        { field: 'Field17', width: 140 },
        { field: 'Field18', width: 140 },
        { field: 'Field19', width: 140 },
        { field: 'Field20', width: 140 },
        { field: 'Field21', width: 140 },
        { field: 'Field22', width: 140 },
        { field: 'Field23', width: 140 },
        { field: 'Field24', width: 140 },
        { field: 'Field25', width: 140 },
        { field: 'Field26', width: 140 },
        { field: 'Field27', width: 140 },
        { field: 'Field28', width: 140 },
        { field: 'Field29', width: 140 },
        { field: 'Field30', width: 140 },
        { field: 'Field31', width: 140 },
        { field: 'Field32', width: 140 },
        { field: 'Field33', width: 140 },
        { field: 'Field34', width: 140 },
        { field: 'Field35', width: 140 },
        { field: 'Field36', width: 140 },
        { field: 'Field37', width: 140 },
        { field: 'Field38', width: 140 },
        { field: 'Field39', width: 140 },
        { field: 'Field40', width: 140 },
        { field: 'Field41', width: 140 },
        { field: 'Field42', width: 140 },
        { field: 'Field43', width: 140 },
        { field: 'Field44', width: 140 },
        { field: 'Field45', width: 140 },
        { field: 'Field46', width: 140 },
        { field: 'Field47', width: 140 },
        { field: 'Field48', width: 140 },
        { field: 'Field49', width: 140 },
        { field: 'Field50', width: 140 },
    ],
    contextMenuItems: ['AutoFit', 'AutoFitAll', 'SortAscending', 'SortDescending',
        'Copy', 'Edit', 'Delete', 'Save', 'Cancel',
        'PdfExport', 'ExcelExport', 'CsvExport', 'FirstPage', 'PrevPage',
        'LastPage', 'NextPage'],
});
grid.appendTo('#Grid');
function ddChange(args) {
    grid.filterSettings.type = args.value;
}
function btnClick1(args) {
    grid.showColumns(dropDownListObject2.value, 'field');
}
function btnClick2(args) {
    grid.hideColumns(dropDownListObject2.value, 'field');
}
document.getElementById('btn1').addEventListener('click', btnClick1);
document.getElementById('btn2').addEventListener('click', btnClick2);